# Generated by Django 2.2 on 2019-08-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190825_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='reviews',
            field=models.ManyToManyField(blank=True, null=True, to='core.Reviews'),
        ),
    ]
